[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1.0"
  JEKYLL_ENV = "production"

# Redirect rules for clean URLs and admin access
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Handle Jekyll's baseurl for Netlify deployment
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://identity.netlify.com https://static.cloudflareinsights.com https://media-library.cloudinary.com; style-src 'self' 'unsafe-inline' https://unpkg.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; img-src 'self' data: https: blob:; font-src 'self' data: https://cdnjs.cloudflare.com; connect-src 'self' https://cloudflareinsights.com https://api.netlify.com https://*.netlify.com https://api.cloudinary.com; frame-src https://player.vimeo.com https://www.youtube.com"
