[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1.0"
  JEKYLL_ENV = "production"

# Redirect rules for clean URLs and admin access
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Handle Jekyll's baseurl for Netlify deployment
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
