backend:
  name: git-gateway
  branch: main # Branch to update (main or master)

# Uncomment below for local development
# local_backend: true

media_folder: "assets/images/uploads" # Media files will be stored in the repo under assets/images/uploads
public_folder: "/assets/images/uploads" # The src attribute for uploaded media will start with /assets/images/uploads

# Cloudinary media library integration
# To enable: Sign up at cloudinary.com, get your cloud_name and api_key,
# then uncomment the lines below and fill in your credentials
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: circleseven
    api_key: 732138267195618
    multiple: true
    insert_transformation: true
    default_transformations:
      - - fetch_format: auto
          quality: auto

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Configuration"
        name: "config"
        file: "_config.yml"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
