backend:
  name: git-gateway
  branch: main # Branch to update (main or master)

# Site URLs - Adds "View Site" link in CMS and shows deploy status
site_url: https://circleseven.co.uk
display_url: https://circleseven.co.uk
logo_url: https://circleseven.co.uk/assets/images/favicon.svg

# Uncomment below for local development
# local_backend: true

media_folder: "assets/images/uploads" # Media files will be stored in the repo under assets/images/uploads
public_folder: "/assets/images/uploads" # The src attribute for uploaded media will start with /assets/images/uploads

# Cloudinary media library integration
# To enable: Sign up at cloudinary.com, get your cloud_name and api_key,
# then uncomment the lines below and fill in your credentials
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: circleseven
    api_key: 732138267195618
    multiple: true
    max_files: 1000
    insert_transformation: true
    default_transformations:
      - - fetch_format: auto
          quality: auto

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    label_singular: "Blog Post"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    # Collection view options
    view_filters:
      - label: "Academic Posts"
        field: categories
        pattern: "Academic"
      - label: "Tutorial Posts"
        field: categories
        pattern: "Tutorial"
    view_groups:
      - label: "Year"
        field: date
        pattern: \d{4}
      - label: "Category"
        field: categories
    sortable_fields: ['title', 'date', 'categories']
    summary: "{{title}}"
    fields: # The fields for each document
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        required: false
        options:
          - Projects
          - Photography
          - Retro Computing
          - Motion Graphics
          - Digital Art and Technology
          - "DAT401 - Strategies for Digital Art and Technology"
          - "DAT402 - Digital Culture"
          - "DAT403 - Digital Media Design"
          - "DAT404 - Web Technologies"
          - "DAT405 - Creative Coding"
          - "DAT406 - Digital Making"
          - "DAT501 - Strategies for Digital Art and Technology"
          - "DAT503 - Reflexive Design"
          - "DAT504 - Advanced Web Technologies"
          - "DAT505 - Advanced Creative Coding"
          - "DAT506 - Emerging Technologies"
          - "DAT601 - Realtime"
          - "DAT602 - Everyware"
          - "DAT612 - Final Year Project"
          - "DAT613 - Dissertation"
          - "INDE601 - Netscapes"
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        required: false
        options:
          - Photography
          - Academic
          - Tutorial
          - Web Development
          - JavaScript
          - Python
          - Photoshop
          - Illustrator
          - After Effects
          - Blender
          - Unity
          - Arduino
          - Photogrammetry
          - Video
          - Sound
          - DAT401
          - DAT402
          - DAT403
          - DAT404
          - DAT405
          - DAT406
          - DAT501
          - DAT503
          - DAT504
          - DAT505
          - DAT506
          - DAT601
          - DAT602
          - DAT612
          - DAT613
          - INDE601
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['title', 'permalink']
    summary: "{{title}} ({{permalink}})"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Configuration"
        name: "config"
        file: "_config.yml"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Related Posts Count", name: "related_posts_count", widget: "number", default: 4, value_type: "int", min: 1, max: 10, step: 1, hint: "Number of related posts to show at the bottom of each post"}
      - label: "Taxonomy (Categories & Tags)"
        name: "taxonomy"
        file: "_data/taxonomy.yml"
        description: "Manage categories and tags used throughout the site. After saving changes here, run 'npm run sync-taxonomy' to update the post editor checkboxes."
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            allow_add: true
            collapsed: false
            summary: "{{fields.item}}"
            field:
              label: "Category Name"
              name: "item"
              widget: "string"
            hint: "Add, edit, or remove categories. Click '+ Add Category' to create new ones. Categories help organize posts into major themes (e.g., Projects, Photography, Academic)."
          - label: "Tags"
            name: "tags"
            widget: "list"
            allow_add: true
            collapsed: false
            summary: "{{fields.item}}"
            field:
              label: "Tag Name"
              name: "item"
              widget: "string"
            hint: "Add, edit, or remove tags. Click '+ Add Tag' to create new ones. Tags provide granular content classification (e.g., Python, Photoshop, Tutorial)."
